2022/09/22 12:12:48 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:12:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:12:49 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:49 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:12:50 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:50 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:50 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:12:50 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:50 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:51 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:12:51 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:51 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:51 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:12:52 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:52 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:52 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:12:52 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:52 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:53 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:12:53 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:53 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:54 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:12:55 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:12:55 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:12:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:12:56 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:12:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:12:56 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:12:57 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:12:57 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:13:01 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 2.4 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            7.8 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                4.8 kB/s | 4.7 kB     00:00    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:01 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum remove export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; qemu-kvm -y
2022/09/22 12:13:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
bash: qemu-kvm: command not found
 

2022/09/22 12:13:03 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; libvirt -y
2022/09/22 12:13:04 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:03 ago on Thu 22 Sep 2022 02:42:11 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:13:04 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: libvirt: command not found
 

2022/09/22 12:13:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python3-libvirt -y
2022/09/22 12:13:05 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:42:11 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:13:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: python3-libvirt: command not found
 

2022/09/22 12:13:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;virt-install -y
2022/09/22 12:13:07 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:06 ago on Thu 22 Sep 2022 02:42:11 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:13:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: -y
 

2022/09/22 12:13:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install iperf -y
2022/09/22 12:13:09 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install wget -y
2022/09/22 12:13:10 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:09 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:10 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install virt-manager -y
2022/09/22 12:13:11 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:11 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install tigervnc -y
2022/09/22 12:13:13 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:12 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install systemd-devel -y
2022/09/22 12:13:14 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:13:16 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:13:17 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:13:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:13:17 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:13:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install gcc-c++ -y
2022/09/22 12:13:19 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:19 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rust -y
2022/09/22 12:13:20 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:19 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install python36-devel -y
2022/09/22 12:13:22 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:21 ago on Thu 22 Sep 2022 02:42:11 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:13:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:13:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install xmltodict +  
2022/09/22 12:13:22 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install xmltodict +  '
 

2022/09/22 12:13:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install wcwidth +  
2022/09/22 12:13:23 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:23 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install wcwidth +  '
 

2022/09/22 12:13:23 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pathlib2 +  
2022/09/22 12:13:24 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pathlib2 +  '
 

2022/09/22 12:13:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install artifactory +  
2022/09/22 12:13:24 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:24 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install artifactory +  '
 

2022/09/22 12:13:25 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install anybadge +  
2022/09/22 12:13:25 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install anybadge +  '
 

2022/09/22 12:13:26 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pyqt5 +  
2022/09/22 12:13:26 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:26 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pyqt5 +  '
 

2022/09/22 12:13:26 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pywin32 +  
2022/09/22 12:13:27 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:27 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pywin32 +  '
 

2022/09/22 12:13:27 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install prettytable +  
2022/09/22 12:13:27 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:27 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install prettytable +  '
 

2022/09/22 12:13:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install bcrypt +  
2022/09/22 12:13:28 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install bcrypt +  '
 

2022/09/22 12:13:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install setuptools_rust +  
2022/09/22 12:13:29 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:29 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install setuptools_rust +  '
 

2022/09/22 12:13:29 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install cffi +  
2022/09/22 12:13:29 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:29 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install cffi +  '
 

2022/09/22 12:13:30 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install cryptography +  
2022/09/22 12:13:30 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:30 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install cryptography +  '
 

2022/09/22 12:13:30 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install prettytable +  
2022/09/22 12:13:31 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install prettytable +  '
 

2022/09/22 12:13:31 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install pynacl +  
2022/09/22 12:13:31 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install pynacl +  '
 

2022/09/22 12:13:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install paramiko +  
2022/09/22 12:13:32 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install paramiko +  '
 

2022/09/22 12:13:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install scp +  
2022/09/22 12:13:33 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:13:33 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install scp +  '
 

