2022/09/22 12:15:31 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:15:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:15:32 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:15:33 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:33 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:15:33 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:33 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:34 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:15:34 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:34 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:35 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:15:35 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:35 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:35 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:15:35 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:35 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:36 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:15:36 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:36 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:37 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 12:15:38 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 12:15:38 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:15:39 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:15:39 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:15:39 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:40 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:15:40 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:15:40 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; yum update -y
2022/09/22 12:15:45 - Terminal_Log - INFO      - log_save.py : 22 line - out: CentOS-8 - Base                                 3.2 kB/s | 3.9 kB     00:01    
CentOS-8 - AppStream                            6.7 kB/s | 4.3 kB     00:00    
CentOS-8 Extra Packages - x86_64                3.5 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:15:45 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:15:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum remove export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; qemu-kvm -y
2022/09/22 12:15:46 - Terminal_Log - INFO      - log_save.py : 22 line - out: No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:15:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err: No packages marked for removal.
bash: qemu-kvm: command not found
 

2022/09/22 12:15:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; libvirt -y
2022/09/22 12:15:47 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:03 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:47 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: libvirt: command not found
 

2022/09/22 12:15:48 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python3-libvirt -y
2022/09/22 12:15:49 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:49 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: python3-libvirt: command not found
 

2022/09/22 12:15:49 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;virt-install -y
2022/09/22 12:15:50 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:06 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:50 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
usage: virt-install --name NAME --memory MB STORAGE INSTALL [options]
virt-install: error: unrecognized arguments: -y
 

2022/09/22 12:15:51 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;iperf -y
2022/09/22 12:15:52 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:52 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
iperf: option requires an argument -- y
Usage: iperf [-s|-c host] [options]
Try `iperf --help' for more information.
 

2022/09/22 12:15:52 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;wget -y
2022/09/22 12:15:53 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:09 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:53 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
wget: invalid option -- 'y'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
 

2022/09/22 12:15:53 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;virt-manager -y
2022/09/22 12:15:55 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:55 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(virt-manager:42971): Gtk-WARNING **: 02:45:05.168: cannot open display: 
 

2022/09/22 12:15:55 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;tigervnc -y
2022/09/22 12:15:56 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:12 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:56 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: tigervnc: command not found
 

2022/09/22 12:15:56 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;systemd-devel -y
2022/09/22 12:15:57 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:57 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: systemd-devel: command not found
 

2022/09/22 12:15:58 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:15:59 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:15:59 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: rpm-build: command not found
 

2022/09/22 12:15:59 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:16:00 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:16:00 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
asciidoc: Too many arguments

Man page:     asciidoc --help manpage
Syntax:       asciidoc --help syntax
 

2022/09/22 12:16:00 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:16:01 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;gcc-c++ -y
2022/09/22 12:16:02 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:16:02 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: gcc-c++: command not found
 

2022/09/22 12:16:02 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;rust -y
2022/09/22 12:16:03 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:19 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:16:03 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: rust: command not found
 

2022/09/22 12:16:04 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;python36-devel -y
2022/09/22 12:16:05 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:21 ago on Thu 22 Sep 2022 02:44:54 AM IST.
No match for argument: export
No match for argument: http_proxy=http://proxy-iind.intel.com:911
 

2022/09/22 12:16:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: export http_proxy=http://proxy-iind.intel.com:911
bash: python36-devel: command not found
 

2022/09/22 12:16:05 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;xmltodict +  
2022/09/22 12:16:05 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:05 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;xmltodict +  '
 

2022/09/22 12:16:06 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;wcwidth +  
2022/09/22 12:16:06 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:06 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;wcwidth +  '
 

2022/09/22 12:16:07 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pathlib2 +  
2022/09/22 12:16:07 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pathlib2 +  '
 

2022/09/22 12:16:07 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;artifactory +  
2022/09/22 12:16:07 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:07 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;artifactory +  '
 

2022/09/22 12:16:08 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;anybadge +  
2022/09/22 12:16:08 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:08 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;anybadge +  '
 

2022/09/22 12:16:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pyqt5 +  
2022/09/22 12:16:09 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:09 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pyqt5 +  '
 

2022/09/22 12:16:09 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pywin32 +  
2022/09/22 12:16:10 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pywin32 +  '
 

2022/09/22 12:16:10 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;prettytable +  
2022/09/22 12:16:10 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:10 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;prettytable +  '
 

2022/09/22 12:16:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;bcrypt +  
2022/09/22 12:16:11 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:11 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;bcrypt +  '
 

2022/09/22 12:16:11 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;setuptools_rust +  
2022/09/22 12:16:12 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;setuptools_rust +  '
 

2022/09/22 12:16:12 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;cffi +  
2022/09/22 12:16:12 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:12 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;cffi +  '
 

2022/09/22 12:16:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;cryptography +  
2022/09/22 12:16:13 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:13 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;cryptography +  '
 

2022/09/22 12:16:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;prettytable +  
2022/09/22 12:16:14 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;prettytable +  '
 

2022/09/22 12:16:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pynacl +  
2022/09/22 12:16:14 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;pynacl +  '
 

2022/09/22 12:16:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;paramiko +  
2022/09/22 12:16:15 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;paramiko +  '
 

2022/09/22 12:16:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;scp +  
2022/09/22 12:16:16 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:16:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;'
bash: -c: line 0: `  ; pip install export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;scp +  '
 

2022/09/22 12:23:31 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 12:23:31 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 12:23:32 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:32 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 12:23:32 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 12:23:33 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:33 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 12:23:34 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:34 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:34 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 12:23:34 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:34 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:35 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 12:23:35 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:35 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:35 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 12:23:36 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:36 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:36 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;; python -m pip install --upgrade pip
2022/09/22 12:23:36 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:36 - Terminal_Log - ERROR     - log_save.py : 28 line - err: bash: -c: line 0: syntax error near unexpected token `;;'
bash: -c: line 0: ` export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;; python -m pip install --upgrade pip'
 

2022/09/22 12:23:37 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 12:23:37 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 12:23:37 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:23:38 - Terminal_Log - INFO      - log_save.py : 22 line - cp ../FILES/Centos-8.repo to /etc/yum.repos.d/Centos-8.repo
2022/09/22 12:23:38 - Terminal_Log - INFO      - log_save.py : 22 line - cp done

2022/09/22 12:23:38 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:  export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911;yum update -y
2022/09/22 12:24:20 - Terminal_Log - INFO      - log_save.py : 22 line - out: Waiting for process with pid 45471 to finish.
CentOS-8 - Base                                 1.5 kB/s | 3.9 kB     00:02    
CentOS-8 - AppStream                            3.3 kB/s | 4.3 kB     00:01    
CentOS-8 Extra Packages - x86_64                3.5 kB/s | 4.7 kB     00:01    
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:20 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: yum remove qemu-kvm -y
2022/09/22 12:24:22 - Terminal_Log - INFO      - log_save.py : 22 line - out: Dependencies resolved.
=================================================================================================
 Package                  Arch    Version                                       Repository   Size
=================================================================================================
Removing:
 qemu-kvm                 x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream    0  
Removing unused dependencies:
 celt051                  x86_64  0.5.1.3-15.el8                                @AppStream  130 k
 edk2-ovmf                noarch  20210527gite1999b264f1f-3.el8                 @AppStream   12 M
 ipxe-roms-qemu           noarch  20181214-8.git133f4c47.el8                    @AppStream  2.6 M
 libibumad                x86_64  35.0-1.el8                                    @BaseOS      41 k
 libpmem                  x86_64  1.6.1-1.el8                                   @AppStream  255 k
 qemu-kvm-block-curl      x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   33 k
 qemu-kvm-block-gluster   x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   37 k
 qemu-kvm-block-iscsi     x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   47 k
 qemu-kvm-block-rbd       x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   33 k
 qemu-kvm-block-ssh       x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   39 k
 qemu-kvm-common          x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream  5.3 M
 qemu-kvm-core            x86_64  15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1    @AppStream   16 M
 rdma-core                x86_64  35.0-1.el8                                    @BaseOS     105 k
 seabios-bin              noarch  1.13.0-2.module_el8.5.0+746+bbd5d70c          @AppStream  384 k
 seavgabios-bin           noarch  1.13.0-2.module_el8.5.0+746+bbd5d70c          @AppStream  210 k
 sgabios-bin              noarch  1:0.20170427git-3.module_el8.5.0+746+bbd5d70c @AppStream  4.0 k
 spice-server             x86_64  0.14.3-4.el8                                  @AppStream  1.2 M

Transaction Summary
=================================================================================================
Remove  18 Packages

Freed space: 38 M
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.   1/1 
  Erasing          : qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.    1/18 
  Erasing          : qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9    2/18 
  Erasing          : libibumad-35.0-1.el8.x86_64                           3/18 
  Running scriptlet: libibumad-35.0-1.el8.x86_64                           3/18 
  Erasing          : spice-server-0.14.3-4.el8.x86_64                      4/18 
  Erasing          : qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+106    5/18 
  Erasing          : qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+    6/18 
  Erasing          : qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+10    7/18 
  Erasing          : qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063    8/18 
  Erasing          : qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063    9/18 
  Erasing          : edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch       10/18 
  Erasing          : ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch     11/18 
  Erasing          : seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.n   12/18 
  Erasing          : seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70   13/18 
  Erasing          : sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+b   14/18 
  Running scriptlet: qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9   15/18 
  Erasing          : qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9   15/18 
  Running scriptlet: qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9   15/18 
  Erasing          : celt051-0.5.1.3-15.el8.x86_64                        16/18 
  Running scriptlet: celt051-0.5.1.3-15.el8.x86_64                        16/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Erasing          : rdma-core-35.0-1.el8.x86_64                          17/18 
  Running scriptlet: rdma-core-35.0-1.el8.x86_64                          17/18 
  Erasing          : libpmem-1.6.1-1.el8.x86_64                           18/18 
  Running scriptlet: libpmem-1.6.1-1.el8.x86_64                           18/18 
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_prg_exec_monitor.so is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so.1.78.0 is empty, not checked.
/sbin/ldconfig: File /usr/local/lib/libboost_coroutine.so is empty, not checked.

  Verifying        : celt051-0.5.1.3-15.el8.x86_64                         1/18 
  Verifying        : edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch        2/18 
  Verifying        : ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch      3/18 
  Verifying        : libibumad-35.0-1.el8.x86_64                           4/18 
  Verifying        : libpmem-1.6.1-1.el8.x86_64                            5/18 
  Verifying        : qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.    6/18 
  Verifying        : qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+106    7/18 
  Verifying        : qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+    8/18 
  Verifying        : qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+10    9/18 
  Verifying        : qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063   10/18 
  Verifying        : qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063   11/18 
  Verifying        : qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9   12/18 
  Verifying        : qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9   13/18 
  Verifying        : rdma-core-35.0-1.el8.x86_64                          14/18 
  Verifying        : seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.n   15/18 
  Verifying        : seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70   16/18 
  Verifying        : sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+b   17/18 
  Verifying        : spice-server-0.14.3-4.el8.x86_64                     18/18 
Installed products updated.

Removed:
  celt051-0.5.1.3-15.el8.x86_64                                                 
  edk2-ovmf-20210527gite1999b264f1f-3.el8.noarch                                
  ipxe-roms-qemu-20181214-8.git133f4c47.el8.noarch                              
  libibumad-35.0-1.el8.x86_64                                                   
  libpmem-1.6.1-1.el8.x86_64                                                    
  qemu-kvm-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64                    
  qemu-kvm-block-curl-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64         
  qemu-kvm-block-gluster-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64      
  qemu-kvm-block-iscsi-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64        
  qemu-kvm-block-rbd-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64          
  qemu-kvm-block-ssh-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64          
  qemu-kvm-common-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64             
  qemu-kvm-core-15:4.2.0-59.module_el8.5.0+1063+c9b9feff.1.x86_64               
  rdma-core-35.0-1.el8.x86_64                                                   
  seabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.noarch                       
  seavgabios-bin-1.13.0-2.module_el8.5.0+746+bbd5d70c.noarch                    
  sgabios-bin-1:0.20170427git-3.module_el8.5.0+746+bbd5d70c.noarch              
  spice-server-0.14.3-4.el8.x86_64                                              

Complete!
 

2022/09/22 12:24:22 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:22 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install libvirt -y
2022/09/22 12:24:23 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:04 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package libvirt-8.0.0-6.module_el8.7.0+1140+ff0772f9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:23 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:24 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install python3-libvirt -y
2022/09/22 12:24:25 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:06 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package python3-libvirt-6.0.0-1.module_el8.5.0+746+bbd5d70c.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:25 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:25 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install virt-install -y
2022/09/22 12:24:26 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:07 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package virt-install-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:26 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:27 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install iperf -y
2022/09/22 12:24:28 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:09 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package iperf-2.1.6-2.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:28 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:28 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install wget -y
2022/09/22 12:24:29 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:10 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package wget-1.19.5-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:29 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:30 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install virt-manager -y
2022/09/22 12:24:31 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:12 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package virt-manager-2.2.1-4.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:31 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:31 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install tigervnc -y
2022/09/22 12:24:32 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:13 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package tigervnc-1.11.0-9.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:32 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:33 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install systemd-devel -y
2022/09/22 12:24:34 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:15 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:34 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:34 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rpm-build autoconf automake libtool pkgconf rpmdevtools -y
2022/09/22 12:24:35 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:16 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package rpm-build-4.14.3-23.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package automake-1.16.1-7.el8.noarch is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package pkgconf-1.4.2-1.el8.x86_64 is already installed.
Package rpmdevtools-8.10-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:35 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:36 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install asciidoc xmlto libuuid-devel json-c-devel kmod-devel libudev-devel -y
2022/09/22 12:24:37 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:18 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package asciidoc-8.6.10-0.5.20180627gitf7c2274.el8.noarch is already installed.
No match for argument: kmod-devel
Package systemd-devel-239-51.el8_5.2.x86_64 is already installed.
 

2022/09/22 12:24:37 - Terminal_Log - ERROR     - log_save.py : 28 line - err: Error: Unable to find a match: kmod-devel
 

2022/09/22 12:24:37 - Terminal_Log - INFO      - log_save.py : 22 line - run the section python_env_step
2022/09/22 12:24:37 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install gcc-c++ -y
2022/09/22 12:24:38 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:19 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package gcc-c++-8.5.0-13.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:38 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:38 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install rust -y
2022/09/22 12:24:39 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:20 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package rust-1.54.0-3.module_el8.5.0+1023+0c63d3d6.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:39 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:40 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad:   yum install python36-devel -y
2022/09/22 12:24:41 - Terminal_Log - INFO      - log_save.py : 22 line - out: Last metadata expiration check: 0:00:22 ago on Thu 22 Sep 2022 02:53:29 AM IST.
Package python36-devel-3.6.8-38.module_el8.5.0+895+a459eca8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 

2022/09/22 12:24:41 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 12:24:41 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install xmltodict  
2022/09/22 12:24:42 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: xmltodict in /usr/local/lib/python3.6/site-packages (0.13.0)
 

2022/09/22 12:24:42 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:42 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install wcwidth  
2022/09/22 12:24:43 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (0.2.5)
 

2022/09/22 12:24:43 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:44 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install pathlib2  
2022/09/22 12:24:44 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pathlib2 in /usr/local/lib/python3.6/site-packages (2.3.7.post1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pathlib2) (1.11.0)
 

2022/09/22 12:24:44 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:45 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install artifactory  
2022/09/22 12:24:45 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: artifactory in /usr/local/lib/python3.6/site-packages (0.1.17)
Requirement already satisfied: pathlib in /usr/local/lib/python3.6/site-packages (from artifactory) (1.0.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from artifactory) (2.20.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from artifactory) (2.6.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->artifactory) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->artifactory) (3.0.4)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->artifactory) (2.5)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->artifactory) (1.24.2)
 

2022/09/22 12:24:45 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:46 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install anybadge  
2022/09/22 12:24:46 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: anybadge in /usr/local/lib/python3.6/site-packages (1.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from anybadge) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->anybadge) (3.0.9)
 

2022/09/22 12:24:46 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:47 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install pyqt5  
2022/09/22 12:24:47 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pyqt5 in /usr/local/lib64/python3.6/site-packages (5.15.6)
Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /usr/local/lib64/python3.6/site-packages (from pyqt5) (12.9.1)
 

2022/09/22 12:24:47 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 12:24:48 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: pip install pywin32  
