2022/09/22 13:01:13 - Terminal_Log - INFO      - log_save.py : 22 line - run the section pre_step
2022/09/22 13:01:13 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization
2022/09/22 13:01:14 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:14 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/imgs
2022/09/22 13:01:14 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:14 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/tools
2022/09/22 13:01:15 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:15 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:15 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/vt_sut_linux_tools
2022/09/22 13:01:16 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:16 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/domains/virtualization/virtualization_inband
2022/09/22 13:01:16 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:16 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:17 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /home/BKCPkg/tools
2022/09/22 13:01:17 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:17 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/python; ln -s /usr/bin/python3.6 /usr/bin/python
2022/09/22 13:01:18 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:18 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; rm -rf /usr/bin/pip;ln -s /usr/bin/pip3.6 /usr/bin/pip
2022/09/22 13:01:18 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:18 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

2022/09/22 13:01:19 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; python -m pip install --upgrade pip
2022/09/22 13:01:20 - Terminal_Log - INFO      - log_save.py : 22 line - out: Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.3.1)
 

2022/09/22 13:01:20 - Terminal_Log - ERROR     - log_save.py : 28 line - err: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 

2022/09/22 13:01:21 - Terminal_Log - INFO      - log_save.py : 22 line - run commnad: export http_proxy=http://proxy-iind.intel.com:911; export https_proxy=http://proxy-iind.intel.com:911; mkdir -p /etc/yum.repos.d/repos.bak; mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repos.bak
2022/09/22 13:01:21 - Terminal_Log - INFO      - log_save.py : 22 line - out:  

2022/09/22 13:01:21 - Terminal_Log - ERROR     - log_save.py : 28 line - err:  

